### ISSUE TITLE
Docker build failed for stacapi 2.4.5

### ISSUE THREAD

**Issue by ramanakoppula** [stac-utils/stac-fastapi#562] opened 2023-04-21 04:52 UTC
Hi Team,
    
     I am using Terraform to deploy latest spac api image to Azure aks container. We are  facing failure druing pip install. Here is the example trace information:

Step 7/7 : RUN pip install -e ./stac_fastapi/types[dev] &&     pip install -e ./stac_fastapi/api[dev] &&     pip install -e ./stac_fastapi/extensions[dev] &&     pip install -e ./stac_fastapi/sqlalchemy[dev,server] &&     pip install -e ./stac_fastapi/pgstac[dev,server]
 ---> Running in a59e17c285c3
**ERROR: ./stac_fastapi/types[dev] is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).**
WARNING: You are using pip version 22.0.4; however, version 23.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
The command '/bin/sh -c pip install -e ./stac_fastapi/types[dev] &&     pip install -e ./stac_fastapi/api[dev] &&     pip install -e ./stac_fastapi/extensions[dev] &&     pip install -e ./stac_fastapi/sqlalchemy[dev,server] &&     pip install -e ./stac_fastapi/pgstac[dev,server]' returned a non-zero code: 1
##[error]Script failed with exit code: 1

**Comment by gadomski** [comment] 2023-04-21 13:28
I can't reproduce with the following commands:

```shell
$ git checkout 2.4.5
$ docker-compose build --no-cache
```

Closing as "needs more information". If you can provide more information about the commands you're running, the dockerfile you're using, etc, feel free to reopen with that info.

**Closed by gadomski** 2023-04-21 13:28 UTC
Labels: bug
