### ISSUE TITLE
Server error when deleting and re-creating collections with identical ID

### ISSUE THREAD

**Issue by ChristineSeeliger** [stac-utils/stac-fastapi#584] opened 2023-06-26 23:48 UTC
We've just came across this issue when deleting and re-creating STAC collections and Items:
If we delete a stac item and their parent collection and recreate both with the same id they had previously, the collection is created properly, but the item will not be created. Instead Stac server returns a 500 error {"code":"UndefinedTableError","description":"relation \"_items_71\" does not exist"}.

**Comment by remicres** [comment] 2024-01-05 14:02
We are facing the same issue. In our case we can't create a single new item in the collection, it looks like something is not done right in the database when a collection is deleted, then re-created.

**Comment by mmcfarland** [comment] 2024-01-05 14:11
Hi @remicres see https://github.com/stac-utils/stac-fastapi/issues/597 which is likely the same cause. The fix is to upgrade the pgstac database version.

**Comment by jonhealy1** [comment] 2024-04-08 15:31
Hi. Can this be closed? It looks like a problem specific to stac-fastapi-pgstac which now lives in another repository.

**Comment by remicres** [comment] 2024-04-08 15:39
On my side I would say "yes", the problem is fixed in the other repository

**Comment by jonhealy1** [comment] 2024-04-08 15:43
Closing

**Closed by jonhealy1** 2024-04-08 15:43 UTC
Labels: bug
