### ISSUE TITLE
Add integration tests against pystac-client

### ISSUE THREAD

**Issue by geospatial-jeff** [stac-utils/stac-fastapi#212] opened 2021-08-07 21:17 UTC
This API should work well with pystac-client.  We need integration tests to make sure this is the case.

https://github.com/stac-utils/pystac-client

First brought up in #207.

**Comment by geospatial-jeff** [comment] 2022-08-04 13:21
Ideally these tests are done against the API layer instead of individual backends.

**Comment by martys** [comment] 2023-04-04 10:49
1 up - as currently the API is successfully spitting out responses that **pystac** [library ](https://github.com/stac-utils/pystac)is not able to parse. 
In other words the responses are not STAC compliant :(  
(in our case license field was missing)

**Comment by gadomski** [comment] 2023-04-04 11:07
> In other words the responses are not STAC compliant :( (in our case license field was missing)

@martys, can you provide an reproducable example? There's [validation in the test suite](https://github.com/stac-utils/stac-fastapi/blob/01bc0d58697743e870a768b0d486dde7bd567d9f/stac_fastapi/pgstac/tests/resources/test_item.py#L111-L136) so it's surprising to me that **stac-fastapi** is not producing valid STAC.

Note that if you're using the [fields extension](https://github.com/stac-api-extensions/fields), you might not be returning valid STAC by design.

**Comment by martys** [comment] 2023-04-05 12:40
@gadomski - sure. Here's an example of a collection that we have in our database, that is successfully returned by the API - and that the PyStac client refuses to parse, due to the lack of 'license' field

  ```
  {
      "id": "elsegundo_powerpole_drone_deploy_rgb",
      "type": "Collection",
      "title": "ElSegundo Powerpoles - DroneDeploy (RGB)",
      "extent": {
        "spatial": {
          "bbox": [
            [
              -118.423123,
              33.906993,
              -118.401384,
              33.916271
            ]
          ]
        },
        "temporal": {
          "interval": [
            [
              "2021-01-01T21:39:14Z",
              "2021-06-30T08:15:54Z"
            ]
          ]
        }
      },
      "keywords": [
        "DroneDeploy",
        "United States",
        "ElSegundo",
        "Powerpoles"
      ],
      "platform": "Unmanned Drones",
      "serviceId": "1500001156",
      "short_desc": "Drone images of powerpoles of ElSegundo, captured via dronedeploy",
      "description": "Drone images of powerpoles of ElSegundo, captured via dronedeploy",
      "stac_version": "1.0.0",
      "links": [
        {
          "rel": "items",
          "type": "application/geo+json",
          "href": "https://api.azure.com/collections/elsegundo_powerpole_drone_deploy_rgb/items"
        },
        {
          "rel": "parent",
          "type": "application/json",
          "href": "https://api.azure.com/"
        },
        {
          "rel": "root",
          "type": "application/json",
          "href": "https://api.azure.com/"
        },
        {
          "rel": "self",
          "type": "application/json",
          "href": "https://api.azure.com/collections/elsegundo_powerpole_drone_deploy_rgb"
        }
      ]
    }
```

**Comment by gadomski** [comment] 2023-04-05 14:10
The [license field](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#license) is required on Collections ... did you have a `license` attribute on the collection when you added it to the database?

**stac-fastapi** does _not_ validate STAC items before returning them as a part of request. This is a conscious decision, since validation can be slow operation.

**Comment by martys** [comment] 2023-04-05 15:05
hm. Interestingly we're using the **pystac** lib to create catalog and collections in the first place - assuming the use of dedicated objects would ensure that INVALID objects would not get created and stored into the DB. but..  apparently the following was not sufficient to prevent invalid data from getting into the database


 try:
        collection = pystac.Collection(
            id=id,
            title=title,
            description=description,
            extent=extent,
            keywords=keywords,
            extra_fields=dict(
                serviceId=serviceId,
                platform=platform,
                short_desc=short_desc,
            )
        )
        
    except Exception as ex:
        logger.exception(f"exception occurred: {ex}")
        raise PystacUtilsError(f"unable to create collection ({id})")

**Comment by jonhealy1** [comment] 2024-04-11 17:04
Closing but feel free to re-open.

**Closed by jonhealy1** 2024-04-11 17:04 UTC
Labels: enhancement, api layer
